const SeriesData = [
    {   
        id:'1',
        posterimage: "https://picsum.photos/200",
        link: "https://www.youtube.com/watch?v:rrwycJ08PSA",
        title: "Netflix Original Series",
        seriesname: "dark",
        gener: "comedy",
        cast: "Pankaj tripathi KK Menon",
    },
    {
        id:'2',
        posterimage: "https://picsum.photos/200",
        link: "https://www.youtube.com/watch?v:rrwycJ08PSA",
        title: "Amazon Original Series",
        seriesname: "Masaan",
        gener: "Tragedy",
        cast: "Manoj Bajpeyi tripathi KK Menon",
    },
    {
        id:'3',
        posterimage: "https://picsum.photos/200",
        link: "https://www.youtube.com/watch?v:rrwycJ08PSA",
        title: "Amazon Original Series",
        seriesname: "Masaan",
        gener: "Tragedy",
        cast: "Manoj Bajpeyi tripathi KK Menon",
    },
    {
        id:'4',
        posterimage: "https://picsum.photos/200",
        link: "https://www.youtube.com/watch?v:rrwycJ08PSA",
        title: "Amazon Original Series",
        seriesname: "Masaan",
        gener: "Tragedy",
        cast: "Manoj Bajpeyi tripathi KK Menon",
    },
    {
        id:'5',
        posterimage: "https://picsum.photos/200",
        link: "https://www.youtube.com/watch?v:rrwycJ08PSA",
        title: "Amazon Original Series",
        seriesname: "Masaan",
        gener: "Tragedy",
        cast: "Manoj Bajpeyi tripathi KK Menon",
    },
    {
        id:'6',
        posterimage: "https://picsum.photos/200",
        link: "https://www.youtube.com/watch?v:rrwycJ08PSA",
        title: "Amazon Original Series",
        seriesname: "Masaan",
        gener: "Tragedy",
        cast: "Manoj Bajpeyi tripathi KK Menon",
    },
    {
        id:'7',
        posterimage: "https://picsum.photos/200",
        link: "https://www.youtube.com/watch?v:rrwycJ08PSA",
        title: "Amazon Original Series",
        seriesname: "Masaan",
        gener: "Tragedy",
        cast: "Manoj Bajpeyi tripathi KK Menon",
    },
    {
        id:'8',
        posterimage: "https://picsum.photos/200",
        link: "https://www.youtube.com/watch?v:rrwycJ08PSA",
        title: "Amazon Original Series",
        seriesname: "Masaan",
        gener: "Tragedy",
        cast: "Manoj Bajpeyi tripathi KK Menon",
    },
   
]
export default SeriesData;